In [1]:
import pandas as pd 

df=pd.read_csv("data.csv")

print("Original Data")
print(df)

reshaped_data=df.values.reshape(-1,1)
print("Reshaped Data")
print(reshaped_data)


# stacked_data=df.stack()
# print("Stacked Data")
# print(stacked_data)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\royal\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\royal\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\royal\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\royal\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\royal\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\royal\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_lo

AttributeError: _ARRAY_API not found

Original Data
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
Reshaped Data
[[  60. ]
 [ 110. ]
 [ 130. ]
 [ 409.1]
 [  60. ]
 [ 117. ]
 [ 145. ]
 [ 479. ]
 [  60. ]
 [ 103. ]
 [ 135. ]
 [ 340. ]
 [  45. ]
 [ 109. ]
 [ 175. ]
 [ 282.4]
 [  45. ]
 [ 117. ]
 [ 148. ]
 [ 406. ]
 [  60. ]
 [ 102. ]
 [ 127. ]
 [ 300. ]
 [  60. ]
 [ 110. ]
 [ 136. ]
 [ 374. ]
 [  45. ]
 [ 104. ]
 [ 134. ]
 [ 253.3]
 [  30. ]
 [ 109. ]
 [ 133. ]
 [ 195.1]
 [  60. ]
 [  98. ]
 [ 124. ]
 [ 269. ]
 [  60. ]
 [ 103. ]
 [ 147. ]
 [ 329.3]
 [  60. ]
 [ 100

In [2]:
import pandas as pd 

df=pd.read_csv("data.csv")

print("Original Data")
print(df)

filtered_data=df[df["Duration"]>25]
print("Filtered Data")
print(filtered_data)

Original Data
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
Filtered Data
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168  

In [4]:
import pandas as pd 
data={
    "ID":[1,2,3],
    "Name":["Alice","Bob","Charlie"],
    "Age":[20,21,22],
    "Marks":[85,90,95]
}
df=pd.DataFrame(data)
print(df)

data2={
    "ID":[1,2,3],
    "Grade":["A","B","A"]
}
df2=pd.DataFrame(data2)
print(df2)

merged_data=pd.merge(df,df2,on="ID")
print("Merged Data")
print(merged_data)




   ID     Name  Age  Marks
0   1    Alice   20     85
1   2      Bob   21     90
2   3  Charlie   22     95
   ID Grade
0   1     A
1   2     B
2   3     A
Merged Data
   ID     Name  Age  Marks Grade
0   1    Alice   20     85     A
1   2      Bob   21     90     B
2   3  Charlie   22     95     A


In [5]:
import pandas as pd

df=pd.read_csv("data.csv")

print("Original Data")
print(df)

print("missing values in each column:")
print(df.isnull().sum())

df_filled=df.fillna(df.mean())
print("Data after filling missing values with mean:")
print(df_filled)

Original Data
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
missing values in each column:
Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64
Data after filling missing values with mean:
     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290

In [ ]:
from sklearn.preprocessing import Normalizer

data=df_filled.select_dtypes(include=['float64',  'int64'])

normalizer=Normalizer(norm='l2')
normalized_data=normalizer.fit_transform(data)

print("Normalized Data")
print(normalized_data)

Normalized Data
[[0.13417655 0.24599035 0.29071587 0.91486047]
 [0.11595312 0.22610859 0.28022005 0.92569244]
 [0.15594466 0.267705   0.35087549 0.88368642]
 [0.12764699 0.30918937 0.49640494 0.80105575]
 [0.10001136 0.26002954 0.32892625 0.90232471]
 [0.17310918 0.2942856  0.36641442 0.86554588]
 [0.14380924 0.26365027 0.32596761 0.89641093]
 [0.14603165 0.33749536 0.4348498  0.82199592]
 [0.11459566 0.41636424 0.50804077 0.7452538 ]
 [0.1888502  0.30845533 0.39029041 0.8466784 ]
 [0.15797326 0.27118742 0.38703448 0.86700989]
 [0.19906166 0.33176943 0.39812331 0.83174595]
 [0.1546864  0.27327931 0.32999766 0.89022024]
 [0.14313798 0.24810583 0.31490355 0.90487058]
 [0.18608968 0.30394648 0.38148385 0.85291104]
 [0.22069111 0.36046215 0.44138222 0.79154545]
 [0.17466675 0.29111125 0.34933351 0.87333376]
 [0.11115778 0.22231555 0.27665936 0.92826685]
 [0.16411155 0.28172483 0.33642868 0.88346718]
 [0.15335247 0.33055976 0.42597907 0.82810331]
 [0.14767997 0.26582395 0.3224346  0.8964174